import { NextRequest, NextResponse } from 'next/server'
import { supabaseAdmin } from '@/lib/supabase-server'

/**
 * POST /api/admin/polls/link
 * Link a poll to a post via the sm_post_polls junction table
 */
export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const { postId, pollId, position, displayOrder, isAutoGenerated } = body

    if (!postId || !pollId) {
      return NextResponse.json(
        { error: 'postId and pollId are required' },
        { status: 400 }
      )
    }

    // Check if link already exists
    const { data: existing } = await supabaseAdmin
      .from('sm_post_polls')
      .select('id')
      .eq('post_id', postId)
      .eq('poll_id', pollId)
      .single()

    if (existing) {
      return NextResponse.json({
        success: true,
        message: 'Link already exists',
        linkId: existing.id,
      })
    }

    // Create the link
    const { data: link, error } = await supabaseAdmin
      .from('sm_post_polls')
      .insert({
        post_id: postId,
        poll_id: pollId,
        position: position || 'after_content',
        display_order: displayOrder || 0,
        is_auto_generated: isAutoGenerated || false,
      })
      .select()
      .single()

    if (error) {
      console.error('Error linking poll to post:', error)
      return NextResponse.json(
        { error: 'Failed to link poll to post', details: error.message },
        { status: 500 }
      )
    }

    // Update poll's source_post_id if not already set
    await supabaseAdmin
      .from('sm_polls')
      .update({ source_post_id: postId })
      .eq('id', pollId)
      .is('source_post_id', null)

    return NextResponse.json({
      success: true,
      linkId: link.id,
    })
  } catch (error) {
    console.error('Error linking poll to post:', error)
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
}

/**
 * DELETE /api/admin/polls/link
 * Remove a poll-post link
 */
export async function DELETE(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const postId = searchParams.get('postId')
    const pollId = searchParams.get('pollId')

    if (!postId || !pollId) {
      return NextResponse.json(
        { error: 'postId and pollId are required' },
        { status: 400 }
      )
    }

    const { error } = await supabaseAdmin
      .from('sm_post_polls')
      .delete()
      .eq('post_id', postId)
      .eq('poll_id', pollId)

    if (error) {
      console.error('Error unlinking poll from post:', error)
      return NextResponse.json(
        { error: 'Failed to unlink poll from post', details: error.message },
        { status: 500 }
      )
    }

    return NextResponse.json({ success: true })
  } catch (error) {
    console.error('Error unlinking poll from post:', error)
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
}
