// ============================================================================
// Page Registry - Central source of truth for all site pages
// ============================================================================

export type PageCategory =
  | 'homepage'
  | 'team-pages'
  | 'admin'
  | 'studio'
  | 'gm'
  | 'scout'
  | 'fan-engagement'
  | 'polls'
  | 'content'
  | 'auth'
  | 'user'
  | 'static'
  | 'experimental'
  | 'misc'

export interface CronJob {
  id: string
  name: string
  path: string
  schedule: string
  humanSchedule: string
  description: string
  routeFile: string
}

export interface DataSource {
  type: 'supabase-table' | 'api-route' | 'external-api'
  name: string
  database?: 'sm' | 'datalab'
  description?: string
}

export interface PageEntry {
  slug: string
  name: string
  route: string
  category: PageCategory
  description: string
  dataSources: DataSource[]
  cronJobs: string[] // cron job IDs
  keyComponents: string[]
  keyFiles: string[]
  isDynamic: boolean
  requiresAuth: boolean
  requiresAdmin: boolean
  sport?: string
  team?: string
  notes?: string
}

// ============================================================================
// Cron Jobs
// ============================================================================

export const CRON_JOBS: CronJob[] = [
  {
    id: 'sync-teams',
    name: 'Sync Teams',
    path: '/api/cron/sync-teams',
    schedule: '0 * * * *',
    humanSchedule: 'Every hour at :00',
    description: 'Revalidates all team pages and verifies data integrity',
    routeFile: 'src/app/api/cron/sync-teams/route.ts',
  },
  {
    id: 'team-pages-health',
    name: 'Team Pages Health',
    path: '/api/cron/team-pages-health',
    schedule: '15 * * * *',
    humanSchedule: 'Every hour at :15',
    description: 'Full health check with ESPN ID mapping verification',
    routeFile: 'src/app/api/cron/team-pages-health/route.ts',
  },
  {
    id: 'sync-bears-data',
    name: 'Sync Bears Data',
    path: '/api/cron/sync-bears-data',
    schedule: '30 * * * *',
    humanSchedule: 'Every hour at :30',
    description: 'Syncs Bears-specific data from DataLab',
    routeFile: 'src/app/api/cron/sync-bears-data/route.ts',
  },
  {
    id: 'live-games',
    name: 'Live Games',
    path: '/api/cron/live-games',
    schedule: '* * * * *',
    humanSchedule: 'Every minute',
    description: 'Polls live game data with 10-second intervals during active games',
    routeFile: 'src/app/api/cron/live-games/route.ts',
  },
  {
    id: 'send-chicago-daily',
    name: 'Chicago Daily Newsletter',
    path: '/api/cron/send-chicago-daily',
    schedule: '0 12 * * *',
    humanSchedule: 'Daily at 12pm UTC',
    description: 'Sends the Chicago Daily newsletter to subscribers',
    routeFile: 'src/app/api/cron/send-chicago-daily/route.ts',
  },
  {
    id: 'cleanup-scout-history',
    name: 'Cleanup Scout History',
    path: '/api/cron/cleanup-scout-history',
    schedule: '0 3 * * *',
    humanSchedule: 'Daily at 3am UTC',
    description: 'Deletes Scout AI query history older than 30 days',
    routeFile: 'src/app/api/cron/cleanup-scout-history/route.ts',
  },
  {
    id: 'sync-gm-rosters',
    name: 'Sync GM Rosters',
    path: '/api/cron/sync-gm-rosters',
    schedule: '45 * * * *',
    humanSchedule: 'Every hour at :45',
    description: 'Syncs GM trade simulator rosters from DataLab',
    routeFile: 'src/app/api/cron/sync-gm-rosters/route.ts',
  },
  {
    id: 'audit-gm',
    name: 'Audit GM Trades',
    path: '/api/cron/audit-gm',
    schedule: '50 * * * *',
    humanSchedule: 'Every hour at :50',
    description: 'Audits GM trade data and scores for integrity',
    routeFile: 'src/app/api/cron/audit-gm/route.ts',
  },
  {
    id: 'mobile-alerts',
    name: 'Mobile Alerts',
    path: '/api/cron/mobile-alerts',
    schedule: '* * * * *',
    humanSchedule: 'Every minute',
    description: 'Sends mobile push notifications for live events and news',
    routeFile: 'src/app/api/cron/mobile-alerts/route.ts',
  },
  {
    id: 'sync-depth-charts',
    name: 'Sync Depth Charts',
    path: '/api/cron/sync-depth-charts',
    schedule: '55 * * * *',
    humanSchedule: 'Every hour at :55',
    description: 'Syncs depth chart data from DataLab',
    routeFile: 'src/app/api/cron/sync-depth-charts/route.ts',
  },
  {
    id: 'bears-sync-legacy',
    name: 'Bears Sync (Legacy)',
    path: '/api/cron/bears-sync',
    schedule: '',
    humanSchedule: 'Disabled',
    description: 'Legacy Bears data sync — not in vercel.json',
    routeFile: 'src/app/api/cron/bears-sync/route.ts',
  },
  {
    id: 'bears-live-legacy',
    name: 'Bears Live (Legacy)',
    path: '/api/cron/bears-live',
    schedule: '',
    humanSchedule: 'Disabled',
    description: 'Legacy Bears live game sync — not in vercel.json',
    routeFile: 'src/app/api/cron/bears-live/route.ts',
  },
]

// ============================================================================
// Category Configuration
// ============================================================================

const CATEGORY_CONFIG: Record<PageCategory, { label: string; color: string }> = {
  'homepage': { label: 'Homepage', color: '#3b82f6' },
  'team-pages': { label: 'Team Pages', color: '#22c55e' },
  'admin': { label: 'Admin', color: '#ef4444' },
  'studio': { label: 'Studio', color: '#a855f7' },
  'gm': { label: 'GM / Trade Sim', color: '#f59e0b' },
  'scout': { label: 'Scout AI', color: '#06b6d4' },
  'fan-engagement': { label: 'Fan Engagement', color: '#ec4899' },
  'polls': { label: 'Polls', color: '#8b5cf6' },
  'content': { label: 'Content / Shows', color: '#10b981' },
  'auth': { label: 'Auth', color: '#6366f1' },
  'user': { label: 'User', color: '#14b8a6' },
  'static': { label: 'Static', color: '#64748b' },
  'experimental': { label: 'Experimental', color: '#f97316' },
  'misc': { label: 'Misc', color: '#78716c' },
}

// ============================================================================
// Team Pages Helper
// ============================================================================

type TeamKey = 'bears' | 'bulls' | 'blackhawks' | 'cubs' | 'whitesox'

interface TeamConfig {
  key: TeamKey
  name: string
  slug: string
  sport: string
  dataFile: string
  tables: {
    games: string
    players: string
    stats: string
    seasons: string
    teamStats: string
    contracts: string
    salaryCap: string
    live: string
  }
}

const TEAMS: TeamConfig[] = [
  {
    key: 'bears',
    name: 'Chicago Bears',
    slug: 'chicago-bears',
    sport: 'NFL',
    dataFile: 'src/lib/bearsData.ts',
    tables: {
      games: 'bears_games_master',
      players: 'bears_players',
      stats: 'bears_player_game_stats',
      seasons: 'bears_season_record',
      teamStats: 'bears_team_season_stats',
      contracts: 'bears_contracts',
      salaryCap: 'bears_salary_cap',
      live: 'bears_live',
    },
  },
  {
    key: 'bulls',
    name: 'Chicago Bulls',
    slug: 'chicago-bulls',
    sport: 'NBA',
    dataFile: 'src/lib/bullsData.ts',
    tables: {
      games: 'bulls_games_master',
      players: 'bulls_players',
      stats: 'bulls_player_game_stats',
      seasons: 'bulls_seasons',
      teamStats: 'bulls_team_season_stats',
      contracts: 'bulls_contracts',
      salaryCap: 'bulls_salary_cap',
      live: 'bulls_live',
    },
  },
  {
    key: 'blackhawks',
    name: 'Chicago Blackhawks',
    slug: 'chicago-blackhawks',
    sport: 'NHL',
    dataFile: 'src/lib/blackhawksData.ts',
    tables: {
      games: 'blackhawks_games_master',
      players: 'blackhawks_players',
      stats: 'blackhawks_player_game_stats',
      seasons: 'blackhawks_seasons',
      teamStats: 'blackhawks_team_season_stats',
      contracts: 'blackhawks_contracts',
      salaryCap: 'blackhawks_salary_cap',
      live: 'blackhawks_live',
    },
  },
  {
    key: 'cubs',
    name: 'Chicago Cubs',
    slug: 'chicago-cubs',
    sport: 'MLB',
    dataFile: 'src/lib/cubsData.ts',
    tables: {
      games: 'cubs_games_master',
      players: 'cubs_players',
      stats: 'cubs_player_game_stats',
      seasons: 'cubs_seasons',
      teamStats: 'cubs_team_season_stats',
      contracts: 'cubs_contracts',
      salaryCap: 'cubs_salary_cap',
      live: 'cubs_live',
    },
  },
  {
    key: 'whitesox',
    name: 'Chicago White Sox',
    slug: 'chicago-white-sox',
    sport: 'MLB',
    dataFile: 'src/lib/whitesoxData.ts',
    tables: {
      games: 'whitesox_games_master',
      players: 'whitesox_players',
      stats: 'whitesox_player_game_stats',
      seasons: 'whitesox_seasons',
      teamStats: 'whitesox_team_season_stats',
      contracts: 'whitesox_contracts',
      salaryCap: 'whitesox_salary_cap',
      live: 'whitesox_live',
    },
  },
]

function makeTeamPages(team: TeamConfig): PageEntry[] {
  const t = team.tables
  const baseFile = team.dataFile
  const pageDir = `src/app/${team.slug}`

  return [
    {
      slug: `${team.key}-hub`,
      name: `${team.name} Hub`,
      route: `/${team.slug}`,
      category: 'team-pages',
      description: `Main hub page for ${team.name} — record, news, quick links`,
      dataSources: [
        { type: 'supabase-table', name: t.seasons, database: 'datalab', description: 'Season record' },
        { type: 'supabase-table', name: t.games, database: 'datalab', description: 'Upcoming/recent games' },
      ],
      cronJobs: ['sync-teams', 'team-pages-health'],
      keyComponents: [],
      keyFiles: [`${pageDir}/page.tsx`, baseFile, 'src/lib/team-config.ts'],
      isDynamic: false,
      requiresAuth: false,
      requiresAdmin: false,
      sport: team.sport,
      team: team.key,
    },
    {
      slug: `${team.key}-schedule`,
      name: `${team.name} Schedule`,
      route: `/${team.slug}/schedule`,
      category: 'team-pages',
      description: `Full season schedule with scores for completed games`,
      dataSources: [
        { type: 'supabase-table', name: t.games, database: 'datalab', description: 'All games for season' },
      ],
      cronJobs: ['sync-teams'],
      keyComponents: [],
      keyFiles: [`${pageDir}/schedule/page.tsx`, baseFile],
      isDynamic: false,
      requiresAuth: false,
      requiresAdmin: false,
      sport: team.sport,
      team: team.key,
    },
    {
      slug: `${team.key}-scores`,
      name: `${team.name} Scores`,
      route: `/${team.slug}/scores`,
      category: 'team-pages',
      description: `Game scores with box score stats and player stats`,
      dataSources: [
        { type: 'supabase-table', name: t.games, database: 'datalab', description: 'Completed games' },
        { type: 'supabase-table', name: t.stats, database: 'datalab', description: 'Player game stats' },
        { type: 'supabase-table', name: t.players, database: 'datalab', description: 'Player info/headshots' },
      ],
      cronJobs: ['sync-teams'],
      keyComponents: [],
      keyFiles: [`${pageDir}/scores/page.tsx`, baseFile],
      isDynamic: false,
      requiresAuth: false,
      requiresAdmin: false,
      sport: team.sport,
      team: team.key,
    },
    {
      slug: `${team.key}-stats`,
      name: `${team.name} Stats`,
      route: `/${team.slug}/stats`,
      category: 'team-pages',
      description: `Team season stats and player leaderboards`,
      dataSources: [
        { type: 'supabase-table', name: t.teamStats, database: 'datalab', description: 'Team season stats' },
        { type: 'supabase-table', name: t.seasons, database: 'datalab', description: 'Win/loss record' },
        { type: 'supabase-table', name: t.stats, database: 'datalab', description: 'Player stats for leaderboards' },
      ],
      cronJobs: ['sync-teams', 'team-pages-health'],
      keyComponents: [],
      keyFiles: [`${pageDir}/stats/page.tsx`, baseFile],
      isDynamic: false,
      requiresAuth: false,
      requiresAdmin: false,
      sport: team.sport,
      team: team.key,
    },
    {
      slug: `${team.key}-roster`,
      name: `${team.name} Roster`,
      route: `/${team.slug}/roster`,
      category: 'team-pages',
      description: `Active roster driven by contracts table`,
      dataSources: [
        { type: 'supabase-table', name: t.contracts, database: 'datalab', description: 'Roster source of truth' },
        { type: 'supabase-table', name: t.players, database: 'datalab', description: 'Player bio and headshots' },
      ],
      cronJobs: ['sync-teams'],
      keyComponents: [],
      keyFiles: [`${pageDir}/roster/page.tsx`, baseFile],
      isDynamic: false,
      requiresAuth: false,
      requiresAdmin: false,
      sport: team.sport,
      team: team.key,
    },
    {
      slug: `${team.key}-players`,
      name: `${team.name} Players`,
      route: `/${team.slug}/players`,
      category: 'team-pages',
      description: `Player browser with selector and profile view`,
      dataSources: [
        { type: 'supabase-table', name: t.contracts, database: 'datalab', description: 'Active players' },
        { type: 'supabase-table', name: t.players, database: 'datalab', description: 'Player details' },
        { type: 'supabase-table', name: t.stats, database: 'datalab', description: 'Season stats' },
      ],
      cronJobs: ['sync-teams'],
      keyComponents: [],
      keyFiles: [`${pageDir}/players/page.tsx`, baseFile],
      isDynamic: false,
      requiresAuth: false,
      requiresAdmin: false,
      sport: team.sport,
      team: team.key,
    },
    {
      slug: `${team.key}-player-detail`,
      name: `${team.name} Player Detail`,
      route: `/${team.slug}/players/[slug]`,
      category: 'team-pages',
      description: `Individual player profile with bio, stats, and game log`,
      dataSources: [
        { type: 'supabase-table', name: t.players, database: 'datalab', description: 'Player bio' },
        { type: 'supabase-table', name: t.stats, database: 'datalab', description: 'Game-by-game stats' },
        { type: 'supabase-table', name: t.contracts, database: 'datalab', description: 'Contract info' },
      ],
      cronJobs: [],
      keyComponents: [],
      keyFiles: [`${pageDir}/players/[slug]/page.tsx`, baseFile],
      isDynamic: true,
      requiresAuth: false,
      requiresAdmin: false,
      sport: team.sport,
      team: team.key,
    },
    {
      slug: `${team.key}-live`,
      name: `${team.name} Live`,
      route: `/${team.slug}/live`,
      category: 'team-pages',
      description: `Live game data with 10-second polling`,
      dataSources: [
        { type: 'supabase-table', name: t.live, database: 'datalab', description: 'Live game scores' },
        { type: 'supabase-table', name: `${team.key === 'whitesox' ? 'whitesox' : team.key}_player_stats_live`, database: 'datalab', description: 'Live player stats' },
        { type: 'supabase-table', name: 'live_games_registry', database: 'datalab', description: 'Active games registry' },
      ],
      cronJobs: ['live-games'],
      keyComponents: [],
      keyFiles: [`${pageDir}/live/page.tsx`, baseFile],
      isDynamic: false,
      requiresAuth: false,
      requiresAdmin: false,
      sport: team.sport,
      team: team.key,
      notes: 'Polls every 10 seconds during live games, 60 seconds otherwise',
    },
    {
      slug: `${team.key}-cap-tracker`,
      name: `${team.name} Cap Tracker`,
      route: `/${team.slug}/cap-tracker`,
      category: 'team-pages',
      description: `Salary cap breakdown with per-player contracts`,
      dataSources: [
        { type: 'supabase-table', name: t.salaryCap, database: 'datalab', description: 'Team cap summary' },
        { type: 'supabase-table', name: t.contracts, database: 'datalab', description: 'Per-player contracts' },
        { type: 'supabase-table', name: t.players, database: 'datalab', description: 'Headshot joins' },
      ],
      cronJobs: [],
      keyComponents: [],
      keyFiles: [`${pageDir}/cap-tracker/page.tsx`],
      isDynamic: false,
      requiresAuth: false,
      requiresAdmin: false,
      sport: team.sport,
      team: team.key,
      notes: 'All cap tables use season = 2026 regardless of sport',
    },
    {
      slug: `${team.key}-depth-chart`,
      name: `${team.name} Depth Chart`,
      route: `/${team.slug}/depth-chart`,
      category: 'team-pages',
      description: `Position depth chart with injury badges`,
      dataSources: [
        { type: 'supabase-table', name: 'depth_charts', database: 'datalab', description: 'Depth chart positions' },
        { type: 'supabase-table', name: t.players, database: 'datalab', description: 'Player info' },
      ],
      cronJobs: ['sync-depth-charts'],
      keyComponents: [],
      keyFiles: [`${pageDir}/depth-chart/page.tsx`],
      isDynamic: false,
      requiresAuth: false,
      requiresAdmin: false,
      sport: team.sport,
      team: team.key,
    },
    {
      slug: `${team.key}-draft-tracker`,
      name: `${team.name} Draft Tracker`,
      route: `/${team.slug}/draft-tracker`,
      category: 'team-pages',
      description: `Draft pick tracking and prospect analysis`,
      dataSources: [
        { type: 'external-api', name: 'DataLab Draft API', description: 'Draft data from DataLab' },
      ],
      cronJobs: [],
      keyComponents: [],
      keyFiles: [`${pageDir}/draft-tracker/page.tsx`],
      isDynamic: false,
      requiresAuth: false,
      requiresAdmin: false,
      sport: team.sport,
      team: team.key,
    },
    {
      slug: `${team.key}-trade-rumors`,
      name: `${team.name} Trade Rumors`,
      route: `/${team.slug}/trade-rumors`,
      category: 'team-pages',
      description: `Trade rumor tracker and analysis`,
      dataSources: [],
      cronJobs: [],
      keyComponents: [],
      keyFiles: [`${pageDir}/trade-rumors/page.tsx`],
      isDynamic: false,
      requiresAuth: false,
      requiresAdmin: false,
      sport: team.sport,
      team: team.key,
    },
    {
      slug: `${team.key}-game-center`,
      name: `${team.name} Game Center`,
      route: `/${team.slug}/game-center`,
      category: 'team-pages',
      description: `Game center with live/completed game details`,
      dataSources: [
        { type: 'supabase-table', name: t.games, database: 'datalab', description: 'Game data' },
        { type: 'supabase-table', name: t.stats, database: 'datalab', description: 'Box score stats' },
      ],
      cronJobs: ['live-games'],
      keyComponents: [],
      keyFiles: [`${pageDir}/game-center/page.tsx`, baseFile],
      isDynamic: false,
      requiresAuth: false,
      requiresAdmin: false,
      sport: team.sport,
      team: team.key,
    },
  ]
}

// ============================================================================
// Full Page Registry
// ============================================================================

export const PAGE_REGISTRY: PageEntry[] = [
  // ─── Homepage ───────────────────────────────────────────────────────
  {
    slug: 'home-main',
    name: 'Homepage (Main)',
    route: '/',
    category: 'homepage',
    description: 'Main landing page with news feed, team tickers, and featured content',
    dataSources: [
      { type: 'api-route', name: '/api/homepage', description: 'Homepage data aggregation' },
      { type: 'api-route', name: '/api/feed', description: 'News feed posts' },
    ],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/page.tsx'],
    isDynamic: false,
    requiresAuth: false,
    requiresAdmin: false,
  },
  {
    slug: 'home-redesign',
    name: 'Homepage (Redesign)',
    route: '/home',
    category: 'homepage',
    description: 'Redesigned home page with new layout',
    dataSources: [
      { type: 'api-route', name: '/api/homepage', description: 'Homepage data' },
    ],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/home/page.tsx'],
    isDynamic: false,
    requiresAuth: false,
    requiresAdmin: false,
  },
  {
    slug: 'home-spatial',
    name: 'Homepage (Spatial)',
    route: '/home1',
    category: 'homepage',
    description: 'Spatial Data Interface with self-healing Data Broker',
    dataSources: [
      { type: 'api-route', name: '/api/broker', description: 'Self-healing Data Broker API' },
    ],
    cronJobs: [],
    keyComponents: ['FeatureGrid', 'SentimentMeter', 'VisionShard'],
    keyFiles: ['src/app/home1/page.tsx', 'src/lib/dataBroker.ts', 'src/app/api/broker/route.ts'],
    isDynamic: false,
    requiresAuth: false,
    requiresAdmin: false,
  },

  // ─── Home Sub-pages ─────────────────────────────────────────────────
  {
    slug: 'home-data',
    name: 'Home Data',
    route: '/home/data',
    category: 'homepage',
    description: 'Data section of redesigned home',
    dataSources: [],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/home/data/page.tsx'],
    isDynamic: false,
    requiresAuth: false,
    requiresAdmin: false,
  },
  {
    slug: 'home-scout',
    name: 'Home Scout',
    route: '/home/scout',
    category: 'homepage',
    description: 'Scout AI feature showcase',
    dataSources: [],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/home/scout/page.tsx'],
    isDynamic: false,
    requiresAuth: false,
    requiresAdmin: false,
  },
  {
    slug: 'home-fan-hub',
    name: 'Home Fan Hub',
    route: '/home/fan-hub',
    category: 'homepage',
    description: 'Fan engagement hub showcase',
    dataSources: [],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/home/fan-hub/page.tsx'],
    isDynamic: false,
    requiresAuth: false,
    requiresAdmin: false,
  },
  {
    slug: 'home-simulators',
    name: 'Home Simulators',
    route: '/home/simulators',
    category: 'homepage',
    description: 'GM and mock draft simulator showcase',
    dataSources: [],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/home/simulators/page.tsx'],
    isDynamic: false,
    requiresAuth: false,
    requiresAdmin: false,
  },
  {
    slug: 'home-premium',
    name: 'Home Premium',
    route: '/home/premium',
    category: 'homepage',
    description: 'Premium subscription page',
    dataSources: [],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/home/premium/page.tsx'],
    isDynamic: false,
    requiresAuth: false,
    requiresAdmin: false,
  },

  // ─── Team Pages (65 pages) ─────────────────────────────────────────
  ...TEAMS.flatMap(makeTeamPages),

  // ─── Admin Pages ────────────────────────────────────────────────────
  {
    slug: 'admin-dashboard',
    name: 'Admin Dashboard',
    route: '/admin',
    category: 'admin',
    description: 'Main admin dashboard with site overview and quick actions',
    dataSources: [
      { type: 'supabase-table', name: 'posts', database: 'sm', description: 'Post counts' },
    ],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/admin/page.tsx'],
    isDynamic: false,
    requiresAuth: true,
    requiresAdmin: true,
  },
  {
    slug: 'admin-posts',
    name: 'All Posts',
    route: '/admin/posts',
    category: 'admin',
    description: 'Post management list with search, filters, and bulk actions',
    dataSources: [
      { type: 'supabase-table', name: 'posts', database: 'sm' },
    ],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/admin/posts/page.tsx'],
    isDynamic: false,
    requiresAuth: true,
    requiresAdmin: true,
  },
  {
    slug: 'admin-new-post',
    name: 'New Post',
    route: '/admin/posts/new',
    category: 'admin',
    description: 'Create new article with PostIQ AI assistant',
    dataSources: [
      { type: 'api-route', name: '/api/admin/ai', description: 'PostIQ AI features' },
    ],
    cronJobs: [],
    keyComponents: ['PostEditor', 'AIAssistant'],
    keyFiles: ['src/app/admin/posts/new/page.tsx', 'src/components/admin/PostEditor/AIAssistant.tsx'],
    isDynamic: false,
    requiresAuth: true,
    requiresAdmin: true,
  },
  {
    slug: 'admin-post-detail',
    name: 'Post Detail',
    route: '/admin/posts/[id]',
    category: 'admin',
    description: 'View individual post details',
    dataSources: [
      { type: 'supabase-table', name: 'posts', database: 'sm' },
    ],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/admin/posts/[id]/page.tsx'],
    isDynamic: true,
    requiresAuth: true,
    requiresAdmin: true,
  },
  {
    slug: 'admin-edit-post',
    name: 'Edit Post',
    route: '/admin/posts/[id]/edit',
    category: 'admin',
    description: 'Edit existing post with PostIQ integration',
    dataSources: [
      { type: 'supabase-table', name: 'posts', database: 'sm' },
      { type: 'api-route', name: '/api/admin/ai', description: 'PostIQ AI features' },
    ],
    cronJobs: [],
    keyComponents: ['PostEditor', 'AIAssistant'],
    keyFiles: ['src/app/admin/posts/[id]/edit/page.tsx'],
    isDynamic: true,
    requiresAuth: true,
    requiresAdmin: true,
  },
  {
    slug: 'admin-categories',
    name: 'Categories',
    route: '/admin/categories',
    category: 'admin',
    description: 'Manage post categories and subcategories',
    dataSources: [
      { type: 'supabase-table', name: 'categories', database: 'sm' },
    ],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/admin/categories/page.tsx'],
    isDynamic: false,
    requiresAuth: true,
    requiresAdmin: true,
  },
  {
    slug: 'admin-authors',
    name: 'Authors',
    route: '/admin/authors',
    category: 'admin',
    description: 'Manage post authors and contributor profiles',
    dataSources: [
      { type: 'supabase-table', name: 'authors', database: 'sm' },
    ],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/admin/authors/page.tsx'],
    isDynamic: false,
    requiresAuth: true,
    requiresAdmin: true,
  },
  {
    slug: 'admin-media',
    name: 'Media Library',
    route: '/admin/media',
    category: 'admin',
    description: 'Upload and manage images and media assets',
    dataSources: [
      { type: 'supabase-table', name: 'media', database: 'sm' },
    ],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/admin/media/page.tsx'],
    isDynamic: false,
    requiresAuth: true,
    requiresAdmin: true,
  },
  {
    slug: 'admin-hub',
    name: 'Hub',
    route: '/admin/hub',
    category: 'admin',
    description: 'Content hub management and featured content curation',
    dataSources: [
      { type: 'api-route', name: '/api/hub', description: 'Hub content' },
    ],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/admin/hub/page.tsx'],
    isDynamic: false,
    requiresAuth: true,
    requiresAdmin: true,
  },
  {
    slug: 'admin-charts',
    name: 'Charts',
    route: '/admin/charts',
    category: 'admin',
    description: 'Create and manage data visualization charts',
    dataSources: [
      { type: 'supabase-table', name: 'charts', database: 'sm' },
    ],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/admin/charts/page.tsx'],
    isDynamic: false,
    requiresAuth: true,
    requiresAdmin: true,
  },
  {
    slug: 'admin-new-chart',
    name: 'New Chart',
    route: '/admin/charts/new',
    category: 'admin',
    description: 'Chart creation editor',
    dataSources: [],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/admin/charts/new/page.tsx'],
    isDynamic: false,
    requiresAuth: true,
    requiresAdmin: true,
  },
  {
    slug: 'admin-edit-chart',
    name: 'Edit Chart',
    route: '/admin/charts/[id]/edit',
    category: 'admin',
    description: 'Edit existing chart',
    dataSources: [
      { type: 'supabase-table', name: 'charts', database: 'sm' },
    ],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/admin/charts/[id]/edit/page.tsx'],
    isDynamic: true,
    requiresAuth: true,
    requiresAdmin: true,
  },
  {
    slug: 'admin-polls',
    name: 'Polls',
    route: '/admin/polls',
    category: 'admin',
    description: 'Manage user polls and view results',
    dataSources: [
      { type: 'supabase-table', name: 'polls', database: 'sm' },
    ],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/admin/polls/page.tsx'],
    isDynamic: false,
    requiresAuth: true,
    requiresAdmin: true,
  },
  {
    slug: 'admin-poll-detail',
    name: 'Poll Detail',
    route: '/admin/polls/[id]',
    category: 'admin',
    description: 'View and edit individual poll',
    dataSources: [
      { type: 'supabase-table', name: 'polls', database: 'sm' },
    ],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/admin/polls/[id]/page.tsx'],
    isDynamic: true,
    requiresAuth: true,
    requiresAdmin: true,
  },
  {
    slug: 'admin-postiq',
    name: 'PostIQ',
    route: '/admin/postiq',
    category: 'admin',
    description: 'PostIQ AI content assistant dashboard',
    dataSources: [
      { type: 'api-route', name: '/api/admin/ai', description: 'PostIQ AI backend' },
    ],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/admin/postiq/page.tsx', 'src/app/api/admin/ai/route.ts'],
    isDynamic: false,
    requiresAuth: true,
    requiresAdmin: true,
  },
  {
    slug: 'admin-ai-logging',
    name: 'Scout AI Imports',
    route: '/admin/ai-logging',
    category: 'admin',
    description: 'Scout AI error logs and query monitoring',
    dataSources: [
      { type: 'supabase-table', name: 'scout_errors', database: 'datalab', description: 'Error logs' },
    ],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/admin/ai-logging/page.tsx'],
    isDynamic: false,
    requiresAuth: true,
    requiresAdmin: true,
  },
  {
    slug: 'admin-copilot',
    name: 'Copilot Monitoring',
    route: '/admin/copilot',
    category: 'admin',
    description: 'Admin AI assistant monitoring dashboard',
    dataSources: [],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/admin/copilot/page.tsx'],
    isDynamic: false,
    requiresAuth: true,
    requiresAdmin: true,
  },
  {
    slug: 'admin-team-pages-sync',
    name: 'Team Pages Sync',
    route: '/admin/team-pages-sync',
    category: 'admin',
    description: 'Team pages health check dashboard — monitors data integrity',
    dataSources: [
      { type: 'api-route', name: '/api/cron/team-pages-health', description: 'Health check results' },
    ],
    cronJobs: ['sync-teams', 'team-pages-health'],
    keyComponents: [],
    keyFiles: ['src/app/admin/team-pages-sync/page.tsx'],
    isDynamic: false,
    requiresAuth: true,
    requiresAdmin: true,
  },
  {
    slug: 'admin-twitter-auto-posts',
    name: 'Twitter Auto Posts',
    route: '/admin/twitter-auto-posts',
    category: 'admin',
    description: 'Automated Twitter/X posting management',
    dataSources: [
      { type: 'api-route', name: '/api/admin/twitter-posts', description: 'Twitter post management' },
    ],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/admin/twitter-auto-posts/page.tsx'],
    isDynamic: false,
    requiresAuth: true,
    requiresAdmin: true,
  },
  {
    slug: 'admin-analytics',
    name: 'Analytics',
    route: '/admin/analytics',
    category: 'admin',
    description: 'Site analytics dashboard — views, engagement, traffic',
    dataSources: [
      { type: 'api-route', name: '/api/analytics', description: 'Analytics data' },
    ],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/admin/analytics/page.tsx'],
    isDynamic: false,
    requiresAuth: true,
    requiresAdmin: true,
  },
  {
    slug: 'admin-feed-scoring',
    name: 'Feed Scoring',
    route: '/admin/feed-scoring',
    category: 'admin',
    description: 'Feed algorithm scoring and content ranking configuration',
    dataSources: [],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/admin/feed-scoring/page.tsx'],
    isDynamic: false,
    requiresAuth: true,
    requiresAdmin: true,
  },
  {
    slug: 'admin-user-gm-scoring',
    name: 'User GM Scoring',
    route: '/admin/user-gm-scoring',
    category: 'admin',
    description: 'User trade scores and GM leaderboard management',
    dataSources: [
      { type: 'supabase-table', name: 'gm_leaderboard', database: 'datalab' },
    ],
    cronJobs: ['audit-gm'],
    keyComponents: [],
    keyFiles: ['src/app/admin/user-gm-scoring/page.tsx'],
    isDynamic: false,
    requiresAuth: true,
    requiresAdmin: true,
  },
  {
    slug: 'admin-notifications',
    name: 'Notifications',
    route: '/admin/notifications',
    category: 'admin',
    description: 'Send push notifications to users',
    dataSources: [
      { type: 'api-route', name: '/api/admin/notifications/send', description: 'Send notifications' },
      { type: 'api-route', name: '/api/admin/notifications/history', description: 'Notification history' },
    ],
    cronJobs: ['mobile-alerts'],
    keyComponents: [],
    keyFiles: ['src/app/admin/notifications/page.tsx'],
    isDynamic: false,
    requiresAuth: true,
    requiresAdmin: true,
  },
  {
    slug: 'admin-gm-errors',
    name: 'GM Errors',
    route: '/admin/gm-errors',
    category: 'admin',
    description: 'GM trade simulator error log and debugging',
    dataSources: [
      { type: 'supabase-table', name: 'gm_errors', database: 'datalab' },
    ],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/admin/gm-errors/page.tsx'],
    isDynamic: false,
    requiresAuth: true,
    requiresAdmin: true,
  },
  {
    slug: 'admin-data-cards',
    name: 'Data Cards',
    route: '/admin/data-cards',
    category: 'admin',
    description: 'Stat cards management and generation',
    dataSources: [
      { type: 'supabase-table', name: 'stat_cards', database: 'datalab' },
      { type: 'api-route', name: '/api/admin/data-cards/generate', description: 'Card generation' },
    ],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/admin/data-cards/page.tsx'],
    isDynamic: false,
    requiresAuth: true,
    requiresAdmin: true,
  },
  {
    slug: 'admin-ads',
    name: 'Ads',
    route: '/admin/ads',
    category: 'admin',
    description: 'Advertisement management',
    dataSources: [
      { type: 'api-route', name: '/api/admin/ads', description: 'Ad management' },
    ],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/admin/ads/page.tsx'],
    isDynamic: false,
    requiresAuth: true,
    requiresAdmin: true,
  },
  {
    slug: 'admin-bot',
    name: 'Bot',
    route: '/admin/bot',
    category: 'admin',
    description: 'Twitter bot management and configuration',
    dataSources: [
      { type: 'api-route', name: '/api/bot/config', description: 'Bot configuration' },
      { type: 'api-route', name: '/api/bot/status', description: 'Bot status' },
    ],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/admin/bot/page.tsx'],
    isDynamic: false,
    requiresAuth: true,
    requiresAdmin: true,
  },
  {
    slug: 'admin-settings',
    name: 'Settings',
    route: '/admin/settings',
    category: 'admin',
    description: 'General site settings',
    dataSources: [
      { type: 'api-route', name: '/api/admin/settings', description: 'Site settings' },
    ],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/admin/settings/page.tsx'],
    isDynamic: false,
    requiresAuth: true,
    requiresAdmin: true,
  },
  {
    slug: 'admin-users',
    name: 'Users',
    route: '/admin/users',
    category: 'admin',
    description: 'User management — roles, creation, password resets',
    dataSources: [
      { type: 'supabase-table', name: 'users', database: 'sm' },
    ],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/admin/users/page.tsx'],
    isDynamic: false,
    requiresAuth: true,
    requiresAdmin: true,
  },
  {
    slug: 'admin-subscriptions',
    name: 'Subscriptions',
    route: '/admin/subscriptions',
    category: 'admin',
    description: 'Subscription management and Stripe integration',
    dataSources: [
      { type: 'api-route', name: '/api/admin/subscriptions', description: 'Subscription data' },
    ],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/admin/subscriptions/page.tsx'],
    isDynamic: false,
    requiresAuth: true,
    requiresAdmin: true,
  },

  // ─── Studio ─────────────────────────────────────────────────────────
  {
    slug: 'studio-home',
    name: 'Studio Home',
    route: '/studio',
    category: 'studio',
    description: 'Content creator dashboard for regular users',
    dataSources: [],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/studio/page.tsx'],
    isDynamic: false,
    requiresAuth: true,
    requiresAdmin: false,
  },
  {
    slug: 'studio-posts',
    name: 'Studio Posts',
    route: '/studio/posts',
    category: 'studio',
    description: 'User post management',
    dataSources: [
      { type: 'supabase-table', name: 'posts', database: 'sm' },
    ],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/studio/posts/page.tsx'],
    isDynamic: false,
    requiresAuth: true,
    requiresAdmin: false,
  },
  {
    slug: 'studio-new-post',
    name: 'Studio New Post',
    route: '/studio/posts/new',
    category: 'studio',
    description: 'Create post as contributor',
    dataSources: [],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/studio/posts/new/page.tsx'],
    isDynamic: false,
    requiresAuth: true,
    requiresAdmin: false,
  },
  {
    slug: 'studio-edit-post',
    name: 'Studio Edit Post',
    route: '/studio/posts/[id]/edit',
    category: 'studio',
    description: 'Edit own post',
    dataSources: [
      { type: 'supabase-table', name: 'posts', database: 'sm' },
    ],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/studio/posts/[id]/edit/page.tsx'],
    isDynamic: true,
    requiresAuth: true,
    requiresAdmin: false,
  },
  {
    slug: 'studio-charts',
    name: 'Studio Charts',
    route: '/studio/charts',
    category: 'studio',
    description: 'User chart management',
    dataSources: [
      { type: 'supabase-table', name: 'charts', database: 'sm' },
    ],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/studio/charts/page.tsx'],
    isDynamic: false,
    requiresAuth: true,
    requiresAdmin: false,
  },
  {
    slug: 'studio-new-chart',
    name: 'Studio New Chart',
    route: '/studio/charts/new',
    category: 'studio',
    description: 'Create chart as contributor',
    dataSources: [],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/studio/charts/new/page.tsx'],
    isDynamic: false,
    requiresAuth: true,
    requiresAdmin: false,
  },
  {
    slug: 'studio-polls',
    name: 'Studio Polls',
    route: '/studio/polls',
    category: 'studio',
    description: 'User poll management',
    dataSources: [
      { type: 'supabase-table', name: 'polls', database: 'sm' },
    ],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/studio/polls/page.tsx'],
    isDynamic: false,
    requiresAuth: true,
    requiresAdmin: false,
  },
  {
    slug: 'studio-media',
    name: 'Studio Media',
    route: '/studio/media',
    category: 'studio',
    description: 'User media library',
    dataSources: [
      { type: 'supabase-table', name: 'media', database: 'sm' },
    ],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/studio/media/page.tsx'],
    isDynamic: false,
    requiresAuth: true,
    requiresAdmin: false,
  },

  // ─── GM / Trade Sim ────────────────────────────────────────────────
  {
    slug: 'gm-trade-sim',
    name: 'GM Trade Simulator',
    route: '/gm',
    category: 'gm',
    description: 'AI-powered trade grading simulator — build trades, get Claude AI grades',
    dataSources: [
      { type: 'supabase-table', name: 'gm_trades', database: 'datalab', description: 'Trade history' },
      { type: 'supabase-table', name: 'gm_league_teams', database: 'datalab', description: '124 league teams' },
      { type: 'supabase-table', name: 'gm_sessions', database: 'datalab', description: 'User sessions' },
      { type: 'api-route', name: '/api/gm/grade', description: 'Claude Sonnet AI grading' },
    ],
    cronJobs: ['sync-gm-rosters', 'audit-gm'],
    keyComponents: ['PlayerCard', 'GradeReveal', 'TradeBoard'],
    keyFiles: ['src/app/gm/page.tsx', 'src/app/api/gm/grade/route.ts', 'src/components/gm/PlayerCard.tsx'],
    isDynamic: false,
    requiresAuth: true,
    requiresAdmin: false,
    notes: 'Uses Claude Sonnet 4 via @anthropic-ai/sdk. Rate limit: 10 trades/min',
  },
  {
    slug: 'gm-analytics',
    name: 'GM Analytics',
    route: '/gm/analytics',
    category: 'gm',
    description: 'Trade analytics dashboard with trends and insights',
    dataSources: [
      { type: 'supabase-table', name: 'gm_trades', database: 'datalab' },
      { type: 'api-route', name: '/api/gm/analytics', description: 'Trade analytics' },
    ],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/gm/analytics/page.tsx'],
    isDynamic: false,
    requiresAuth: true,
    requiresAdmin: false,
  },
  {
    slug: 'gm-share',
    name: 'GM Share Trade',
    route: '/gm/share/[code]',
    category: 'gm',
    description: 'Shareable trade result page',
    dataSources: [
      { type: 'supabase-table', name: 'gm_trades', database: 'datalab' },
    ],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/gm/share/[code]/page.tsx'],
    isDynamic: true,
    requiresAuth: false,
    requiresAdmin: false,
  },
  {
    slug: 'mock-draft',
    name: 'Mock Draft',
    route: '/mock-draft',
    category: 'gm',
    description: 'Mock draft simulator — pick prospects for Chicago teams',
    dataSources: [
      { type: 'external-api', name: 'DataLab Draft API', description: 'Draft eligibility & prospects' },
      { type: 'supabase-table', name: 'gm_mock_draft_picks', database: 'datalab', description: 'Draft picks' },
    ],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/mock-draft/page.tsx'],
    isDynamic: false,
    requiresAuth: true,
    requiresAdmin: false,
    notes: 'Eligibility controlled by DataLab — NEVER override on frontend',
  },
  {
    slug: 'mock-draft-share',
    name: 'Mock Draft Share',
    route: '/mock-draft/share/[mockId]',
    category: 'gm',
    description: 'Shareable mock draft result',
    dataSources: [
      { type: 'supabase-table', name: 'gm_mock_draft_picks', database: 'datalab' },
    ],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/mock-draft/share/[mockId]/page.tsx'],
    isDynamic: true,
    requiresAuth: false,
    requiresAdmin: false,
  },

  // ─── Scout AI ───────────────────────────────────────────────────────
  {
    slug: 'scout-ai',
    name: 'Scout AI',
    route: '/scout-ai',
    category: 'scout',
    description: 'AI-powered Chicago sports assistant — answers fan questions via DataLab',
    dataSources: [
      { type: 'api-route', name: '/api/ask-ai', description: 'Proxies to DataLab Perplexity sonar-pro' },
      { type: 'supabase-table', name: 'scout_query_history', database: 'sm', description: '30-day query history' },
    ],
    cronJobs: ['cleanup-scout-history'],
    keyComponents: [],
    keyFiles: ['src/app/scout-ai/page.tsx', 'src/app/api/ask-ai/route.ts', 'src/lib/scoutQueryHistory.ts'],
    isDynamic: false,
    requiresAuth: false,
    requiresAdmin: false,
    notes: 'Maintains session context for follow-up questions. Uses Perplexity sonar-pro via DataLab.',
  },

  // ─── Fan Engagement ─────────────────────────────────────────────────
  {
    slug: 'fan-chat',
    name: 'Fan Chat',
    route: '/fan-chat',
    category: 'fan-engagement',
    description: 'AI-powered team chat channels with unique personalities per team',
    dataSources: [
      { type: 'api-route', name: '/api/fan-chat/ai-response', description: 'AI chat responses' },
    ],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/fan-chat/page.tsx'],
    isDynamic: false,
    requiresAuth: true,
    requiresAdmin: false,
  },
  {
    slug: 'fan-zone',
    name: 'Fan Zone',
    route: '/fan-zone',
    category: 'fan-engagement',
    description: 'Exclusive fan content area',
    dataSources: [],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/fan-zone/page.tsx'],
    isDynamic: false,
    requiresAuth: true,
    requiresAdmin: false,
  },
  {
    slug: 'leaderboards',
    name: 'Leaderboards',
    route: '/leaderboards',
    category: 'fan-engagement',
    description: 'User scores and GM trade leaderboard',
    dataSources: [
      { type: 'supabase-table', name: 'gm_leaderboard', database: 'datalab' },
    ],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/leaderboards/page.tsx'],
    isDynamic: false,
    requiresAuth: false,
    requiresAdmin: false,
  },

  // ─── Polls ──────────────────────────────────────────────────────────
  {
    slug: 'polls-list',
    name: 'Polls',
    route: '/polls',
    category: 'polls',
    description: 'Browse and vote on active polls',
    dataSources: [
      { type: 'supabase-table', name: 'polls', database: 'sm' },
    ],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/polls/page.tsx'],
    isDynamic: false,
    requiresAuth: false,
    requiresAdmin: false,
  },
  {
    slug: 'polls-new',
    name: 'Create Poll',
    route: '/polls/new',
    category: 'polls',
    description: 'Create a new community poll',
    dataSources: [],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/polls/new/page.tsx'],
    isDynamic: false,
    requiresAuth: true,
    requiresAdmin: false,
  },
  {
    slug: 'polls-results',
    name: 'Poll Results',
    route: '/polls/[id]/results',
    category: 'polls',
    description: 'View poll results and vote distribution',
    dataSources: [
      { type: 'supabase-table', name: 'polls', database: 'sm' },
    ],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/polls/[id]/results/page.tsx'],
    isDynamic: true,
    requiresAuth: false,
    requiresAdmin: false,
  },
  {
    slug: 'polls-edit',
    name: 'Edit Poll',
    route: '/polls/[id]/edit',
    category: 'polls',
    description: 'Edit an existing poll',
    dataSources: [
      { type: 'supabase-table', name: 'polls', database: 'sm' },
    ],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/polls/[id]/edit/page.tsx'],
    isDynamic: true,
    requiresAuth: true,
    requiresAdmin: false,
  },
  {
    slug: 'polls-embed',
    name: 'Poll Embed',
    route: '/polls/embed/[id]',
    category: 'polls',
    description: 'Embeddable poll widget for external sites',
    dataSources: [
      { type: 'supabase-table', name: 'polls', database: 'sm' },
    ],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/polls/embed/[id]/page.tsx'],
    isDynamic: true,
    requiresAuth: false,
    requiresAdmin: false,
  },

  // ─── Content / Shows ───────────────────────────────────────────────
  {
    slug: 'bears-film-room',
    name: 'Bears Film Room',
    route: '/bears-film-room',
    category: 'content',
    description: 'Bears video content and film analysis',
    dataSources: [],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/bears-film-room/page.tsx'],
    isDynamic: false,
    requiresAuth: false,
    requiresAdmin: false,
    sport: 'NFL',
    team: 'bears',
  },
  {
    slug: 'pinwheels-and-ivy',
    name: 'Pinwheels & Ivy',
    route: '/pinwheels-and-ivy',
    category: 'content',
    description: 'Cubs video content and analysis',
    dataSources: [],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/pinwheels-and-ivy/page.tsx'],
    isDynamic: false,
    requiresAuth: false,
    requiresAdmin: false,
    sport: 'MLB',
    team: 'cubs',
  },
  {
    slug: 'southside-behavior',
    name: 'Southside Behavior',
    route: '/southside-behavior',
    category: 'content',
    description: 'White Sox video content and analysis',
    dataSources: [],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/southside-behavior/page.tsx'],
    isDynamic: false,
    requiresAuth: false,
    requiresAdmin: false,
    sport: 'MLB',
    team: 'whitesox',
  },
  {
    slug: 'untold-chicago-stories',
    name: 'Untold Chicago Stories',
    route: '/untold-chicago-stories',
    category: 'content',
    description: 'Blackhawks video content and analysis',
    dataSources: [],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/untold-chicago-stories/page.tsx'],
    isDynamic: false,
    requiresAuth: false,
    requiresAdmin: false,
    sport: 'NHL',
    team: 'blackhawks',
  },
  {
    slug: 'vision-theater',
    name: 'Vision Theater',
    route: '/vision-theater',
    category: 'content',
    description: 'Interactive data visualization experience',
    dataSources: [
      { type: 'api-route', name: '/api/vision-theater/comments', description: 'User comments' },
    ],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/vision-theater/page.tsx'],
    isDynamic: false,
    requiresAuth: false,
    requiresAdmin: false,
  },

  // ─── Auth ───────────────────────────────────────────────────────────
  {
    slug: 'login',
    name: 'Login',
    route: '/login',
    category: 'auth',
    description: 'User login page',
    dataSources: [],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/login/page.tsx'],
    isDynamic: false,
    requiresAuth: false,
    requiresAdmin: false,
  },
  {
    slug: 'signup',
    name: 'Signup',
    route: '/signup',
    category: 'auth',
    description: 'User registration page',
    dataSources: [],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/signup/page.tsx'],
    isDynamic: false,
    requiresAuth: false,
    requiresAdmin: false,
  },
  {
    slug: 'forgot-password',
    name: 'Forgot Password',
    route: '/forgot-password',
    category: 'auth',
    description: 'Password reset request',
    dataSources: [],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/forgot-password/page.tsx'],
    isDynamic: false,
    requiresAuth: false,
    requiresAdmin: false,
  },
  {
    slug: 'reset-password',
    name: 'Reset Password',
    route: '/reset-password',
    category: 'auth',
    description: 'Password reset form',
    dataSources: [],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/reset-password/page.tsx'],
    isDynamic: false,
    requiresAuth: false,
    requiresAdmin: false,
  },

  // ─── User ───────────────────────────────────────────────────────────
  {
    slug: 'profile',
    name: 'Profile',
    route: '/profile',
    category: 'user',
    description: 'User profile with favorite teams and preferences',
    dataSources: [
      { type: 'supabase-table', name: 'sm_user_preferences', database: 'sm', description: 'Favorite teams, preferences' },
    ],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/profile/page.tsx'],
    isDynamic: false,
    requiresAuth: true,
    requiresAdmin: false,
  },
  {
    slug: 'notifications-page',
    name: 'Notifications',
    route: '/notifications',
    category: 'user',
    description: 'User notification center',
    dataSources: [],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/notifications/page.tsx'],
    isDynamic: false,
    requiresAuth: true,
    requiresAdmin: false,
  },
  {
    slug: 'my-gm-score',
    name: 'My GM Score',
    route: '/my-gm-score',
    category: 'user',
    description: 'Personal trade scores and history',
    dataSources: [
      { type: 'supabase-table', name: 'gm_trades', database: 'datalab' },
      { type: 'supabase-table', name: 'gm_leaderboard', database: 'datalab' },
    ],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/my-gm-score/page.tsx'],
    isDynamic: false,
    requiresAuth: true,
    requiresAdmin: false,
  },

  // ─── Static ─────────────────────────────────────────────────────────
  {
    slug: 'about',
    name: 'About',
    route: '/about',
    category: 'static',
    description: 'About SportsMockery',
    dataSources: [],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/about/page.tsx'],
    isDynamic: false,
    requiresAuth: false,
    requiresAdmin: false,
  },
  {
    slug: 'contact',
    name: 'Contact',
    route: '/contact',
    category: 'static',
    description: 'Contact form',
    dataSources: [],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/contact/page.tsx'],
    isDynamic: false,
    requiresAuth: false,
    requiresAdmin: false,
  },
  {
    slug: 'privacy',
    name: 'Privacy Policy',
    route: '/privacy',
    category: 'static',
    description: 'Privacy policy',
    dataSources: [],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/privacy/page.tsx'],
    isDynamic: false,
    requiresAuth: false,
    requiresAdmin: false,
  },
  {
    slug: 'terms',
    name: 'Terms of Service',
    route: '/terms',
    category: 'static',
    description: 'Terms of service',
    dataSources: [],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/terms/page.tsx'],
    isDynamic: false,
    requiresAuth: false,
    requiresAdmin: false,
  },
  {
    slug: 'governance',
    name: 'Governance',
    route: '/governance',
    category: 'static',
    description: 'Site governance policies',
    dataSources: [],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/governance/page.tsx'],
    isDynamic: false,
    requiresAuth: false,
    requiresAdmin: false,
  },
  {
    slug: 'pricing',
    name: 'Pricing',
    route: '/pricing',
    category: 'static',
    description: 'Subscription pricing page',
    dataSources: [],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/pricing/page.tsx'],
    isDynamic: false,
    requiresAuth: false,
    requiresAdmin: false,
  },

  // ─── Experimental ───────────────────────────────────────────────────
  {
    slug: 'designs-spotlight',
    name: 'Designs Spotlight',
    route: '/designs/spotlight',
    category: 'experimental',
    description: 'Design system showcase',
    dataSources: [],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/designs/spotlight/page.tsx'],
    isDynamic: false,
    requiresAuth: false,
    requiresAdmin: false,
  },
  {
    slug: 'designs-immersive',
    name: 'Designs Immersive',
    route: '/designs/immersive',
    category: 'experimental',
    description: 'Immersive design exploration',
    dataSources: [],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/designs/immersive/page.tsx'],
    isDynamic: false,
    requiresAuth: false,
    requiresAdmin: false,
  },
  {
    slug: 'designs-ultimate',
    name: 'Designs Ultimate',
    route: '/designs/ultimate',
    category: 'experimental',
    description: 'Ultimate design exploration',
    dataSources: [],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/designs/ultimate/page.tsx'],
    isDynamic: false,
    requiresAuth: false,
    requiresAdmin: false,
  },
  {
    slug: 'ar',
    name: 'AR Experience',
    route: '/ar',
    category: 'experimental',
    description: 'Augmented reality experiment',
    dataSources: [],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/ar/page.tsx'],
    isDynamic: false,
    requiresAuth: false,
    requiresAdmin: false,
  },
  {
    slug: 'ar2',
    name: 'AR Experience 2',
    route: '/ar2',
    category: 'experimental',
    description: 'Second AR experiment',
    dataSources: [],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/ar2/page.tsx'],
    isDynamic: false,
    requiresAuth: false,
    requiresAdmin: false,
  },
  {
    slug: 'ar3',
    name: 'AR Experience 3',
    route: '/ar3',
    category: 'experimental',
    description: 'Third AR experiment',
    dataSources: [],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/ar3/page.tsx'],
    isDynamic: false,
    requiresAuth: false,
    requiresAdmin: false,
  },
  {
    slug: 'metaverse',
    name: 'Metaverse',
    route: '/metaverse',
    category: 'experimental',
    description: 'Metaverse integration test',
    dataSources: [],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/metaverse/page.tsx'],
    isDynamic: false,
    requiresAuth: false,
    requiresAdmin: false,
  },

  // ─── Misc ───────────────────────────────────────────────────────────
  {
    slug: 'feed',
    name: 'Feed',
    route: '/feed',
    category: 'misc',
    description: 'News feed with all posts',
    dataSources: [
      { type: 'api-route', name: '/api/feed', description: 'Feed posts' },
    ],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/feed/page.tsx'],
    isDynamic: false,
    requiresAuth: false,
    requiresAdmin: false,
  },
  {
    slug: 'datahub',
    name: 'DataHub',
    route: '/datahub',
    category: 'misc',
    description: 'Main data hub landing page',
    dataSources: [],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/datahub/page.tsx'],
    isDynamic: false,
    requiresAuth: false,
    requiresAdmin: false,
  },
  {
    slug: 'category-page',
    name: 'Category Page',
    route: '/[category]',
    category: 'misc',
    description: 'Dynamic category archive page',
    dataSources: [
      { type: 'supabase-table', name: 'posts', database: 'sm' },
      { type: 'supabase-table', name: 'categories', database: 'sm' },
    ],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/[category]/page.tsx'],
    isDynamic: true,
    requiresAuth: false,
    requiresAdmin: false,
  },
  {
    slug: 'article-page',
    name: 'Article Page',
    route: '/[category]/[slug]',
    category: 'misc',
    description: 'Individual article page',
    dataSources: [
      { type: 'supabase-table', name: 'posts', database: 'sm' },
    ],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/[category]/[slug]/page.tsx'],
    isDynamic: true,
    requiresAuth: false,
    requiresAdmin: false,
  },
  {
    slug: 'category-datahub',
    name: 'Category DataHub',
    route: '/[category]/datahub',
    category: 'misc',
    description: 'Category-specific data hub',
    dataSources: [],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/[category]/datahub/page.tsx'],
    isDynamic: true,
    requiresAuth: false,
    requiresAdmin: false,
  },
  {
    slug: 'search',
    name: 'Search',
    route: '/search',
    category: 'misc',
    description: 'Search results page',
    dataSources: [
      { type: 'supabase-table', name: 'posts', database: 'sm' },
    ],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/search/page.tsx'],
    isDynamic: false,
    requiresAuth: false,
    requiresAdmin: false,
  },
  {
    slug: 'teams-overview',
    name: 'Teams Overview',
    route: '/teams',
    category: 'misc',
    description: 'All teams overview page',
    dataSources: [],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/teams/page.tsx'],
    isDynamic: false,
    requiresAuth: false,
    requiresAdmin: false,
  },
  {
    slug: 'team-detail',
    name: 'Team Detail',
    route: '/teams/[team]',
    category: 'misc',
    description: 'Individual team overview',
    dataSources: [],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/teams/[team]/page.tsx'],
    isDynamic: true,
    requiresAuth: false,
    requiresAdmin: false,
  },
  {
    slug: 'players-search',
    name: 'Players Search',
    route: '/players',
    category: 'misc',
    description: 'Cross-team player search',
    dataSources: [],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/players/page.tsx'],
    isDynamic: false,
    requiresAuth: false,
    requiresAdmin: false,
  },
  {
    slug: 'player-detail-global',
    name: 'Player Detail',
    route: '/players/[playerId]',
    category: 'misc',
    description: 'Individual player profile page',
    dataSources: [],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/players/[playerId]/page.tsx'],
    isDynamic: true,
    requiresAuth: false,
    requiresAdmin: false,
  },
  {
    slug: 'predictions',
    name: 'Predictions',
    route: '/predictions',
    category: 'misc',
    description: 'Prediction games and contests',
    dataSources: [],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/predictions/page.tsx'],
    isDynamic: false,
    requiresAuth: false,
    requiresAdmin: false,
  },
  {
    slug: 'collectibles',
    name: 'Collectibles',
    route: '/collectibles',
    category: 'misc',
    description: 'NFT and digital collectibles',
    dataSources: [],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/collectibles/page.tsx'],
    isDynamic: false,
    requiresAuth: false,
    requiresAdmin: false,
  },
  {
    slug: 'chat',
    name: 'Chat',
    route: '/chat',
    category: 'misc',
    description: 'Direct messaging',
    dataSources: [
      { type: 'api-route', name: '/api/chat/messages', description: 'Chat messages' },
    ],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/chat/page.tsx'],
    isDynamic: false,
    requiresAuth: true,
    requiresAdmin: false,
  },
  {
    slug: 'live-game',
    name: 'Live Game',
    route: '/live/[sport]/[gameId]',
    category: 'misc',
    description: 'Live game center for any sport/game',
    dataSources: [
      { type: 'api-route', name: '/api/live-games/[gameId]', description: 'Live game data' },
      { type: 'supabase-table', name: 'live_games_registry', database: 'datalab' },
    ],
    cronJobs: ['live-games'],
    keyComponents: [],
    keyFiles: ['src/app/live/[sport]/[gameId]/page.tsx'],
    isDynamic: true,
    requiresAuth: false,
    requiresAdmin: false,
  },
  {
    slug: 'authors-list',
    name: 'Authors',
    route: '/authors',
    category: 'misc',
    description: 'Browse all authors',
    dataSources: [
      { type: 'supabase-table', name: 'authors', database: 'sm' },
    ],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/authors/page.tsx'],
    isDynamic: false,
    requiresAuth: false,
    requiresAdmin: false,
  },
  {
    slug: 'author-profile',
    name: 'Author Profile',
    route: '/author/[id]',
    category: 'misc',
    description: 'Author profile and posts',
    dataSources: [
      { type: 'supabase-table', name: 'authors', database: 'sm' },
      { type: 'supabase-table', name: 'posts', database: 'sm' },
    ],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/author/[id]/page.tsx'],
    isDynamic: true,
    requiresAuth: false,
    requiresAdmin: false,
  },
  {
    slug: 'subscription-success',
    name: 'Subscription Success',
    route: '/subscription/success',
    category: 'misc',
    description: 'Payment confirmation page',
    dataSources: [],
    cronJobs: [],
    keyComponents: [],
    keyFiles: ['src/app/subscription/success/page.tsx'],
    isDynamic: false,
    requiresAuth: true,
    requiresAdmin: false,
  },
]

// ============================================================================
// Utility Functions
// ============================================================================

export function getPageBySlug(slug: string): PageEntry | undefined {
  return PAGE_REGISTRY.find(p => p.slug === slug)
}

export function getPagesByCategory(category: PageCategory): PageEntry[] {
  return PAGE_REGISTRY.filter(p => p.category === category)
}

export function getCategoryConfig(category: PageCategory) {
  return CATEGORY_CONFIG[category]
}

export function getAllCategories(): { category: PageCategory; label: string; color: string; count: number }[] {
  const counts = new Map<PageCategory, number>()
  for (const page of PAGE_REGISTRY) {
    counts.set(page.category, (counts.get(page.category) || 0) + 1)
  }

  return Object.entries(CATEGORY_CONFIG).map(([cat, config]) => ({
    category: cat as PageCategory,
    label: config.label,
    color: config.color,
    count: counts.get(cat as PageCategory) || 0,
  }))
}

export function getCronJobById(id: string): CronJob | undefined {
  return CRON_JOBS.find(c => c.id === id)
}

export function getAllDataSourceNames(): string[] {
  const sources = new Set<string>()
  for (const page of PAGE_REGISTRY) {
    for (const ds of page.dataSources) {
      sources.add(ds.name)
    }
  }
  return Array.from(sources).sort()
}
