import type { Metadata } from 'next'
import { canonicalUrl, JsonLd, breadcrumbJsonLd } from '@/lib/seo'

export const metadata: Metadata = {
  title: 'Editorial Standards',
  description:
    'How Sports Mockery reports, sources, and writes — including our policy on AI tooling. Every article is human-written; Scout (our AI tool) only produces a labeled summary and recap.',
  alternates: { canonical: canonicalUrl('/editorial-standards') },
}

export default function EditorialStandardsPage() {
  return (
    <>
      <JsonLd
        data={breadcrumbJsonLd([
          { name: 'Home', url: '/' },
          { name: 'Editorial Standards', url: '/editorial-standards' },
        ])}
      />
      <article style={{ maxWidth: 720, margin: '0 auto', padding: '48px 16px' }}>
        <h1 style={{ fontSize: 36, fontWeight: 700, marginBottom: 24 }}>Editorial Standards</h1>

        <p style={{ fontSize: 18, lineHeight: 1.7, marginBottom: 20 }}>
          Sports Mockery is a Chicago sports newsroom. We publish news, analysis, rumors, recaps,
          and features about the Bears, Bulls, Cubs, White Sox, and Blackhawks. Everything we
          publish is reported and written by named human staff writers.
        </p>

        <h2 style={{ fontSize: 24, fontWeight: 600, marginTop: 32, marginBottom: 12 }}>
          Our policy on AI
        </h2>
        <p style={{ fontSize: 18, lineHeight: 1.7, marginBottom: 20 }}>
          Every article on Sports Mockery is researched and written by a human staff writer. We
          use an in-house tool called <strong>Scout</strong> to generate two things only: a
          short summary at the top of each article, and a recap at the end. Scout does not write
          the article itself. The byline is always the human author who reported and wrote the
          piece.
        </p>
        <p style={{ fontSize: 18, lineHeight: 1.7, marginBottom: 20 }}>
          When Scout content appears in an article, we label it visibly so readers can tell at a
          glance which paragraphs were AI-generated:
        </p>
        <ul style={{ fontSize: 17, lineHeight: 1.7, marginBottom: 20, paddingLeft: 24 }}>
          <li>
            <strong>Summary · AI-generated by Scout</strong> — a TL;DR-style blurb that appears
            above the article body.
          </li>
          <li>
            <strong>Recap · AI-generated by Scout</strong> — a short wrap-up that appears at the
            end of the article body.
          </li>
        </ul>

        <h2 style={{ fontSize: 24, fontWeight: 600, marginTop: 32, marginBottom: 12 }}>
          Sources and corrections
        </h2>
        <p style={{ fontSize: 18, lineHeight: 1.7, marginBottom: 20 }}>
          Reporting at Sports Mockery follows standard sports-journalism practices: named
          on-the-record sources where possible, clearly attributed reporting from other outlets,
          and direct labeling of opinion vs. analysis vs. news. If we get something wrong, we
          fix the article and add a correction note at the bottom.
        </p>

        <h2 style={{ fontSize: 24, fontWeight: 600, marginTop: 32, marginBottom: 12 }}>
          Article types
        </h2>
        <p style={{ fontSize: 18, lineHeight: 1.7, marginBottom: 20 }}>
          We classify each article as <em>News</em>, <em>Analysis</em>, <em>Rumor</em>,{' '}
          <em>Recap</em>, or <em>Feature</em>. Each type has its own structural standard
          (length, structure, sourcing) that staff writers follow before publishing.
        </p>

        <h2 style={{ fontSize: 24, fontWeight: 600, marginTop: 32, marginBottom: 12 }}>
          Contact
        </h2>
        <p style={{ fontSize: 18, lineHeight: 1.7 }}>
          Questions, tips, or corrections: see <a href="/contact">our contact page</a>.
        </p>
      </article>
    </>
  )
}
