/**
 * Sports Mockery API Client
 *
 * This client fetches ALL data from the website APIs.
 * The mobile app is a thin client - no local content storage.
 * When the website is updated, the app gets fresh data on next fetch.
 */

import { API_BASE_URL } from './config'

// ─── Block content normalization ───────────────────────────────
// Articles authored with the block editor are stored as JSON
// (sometimes wrapped in <!-- SM_BLOCKS -->...<!-- /SM_BLOCKS --> markers).
// The mobile WebView renders HTML, so we need to convert blocks → HTML
// before passing to the renderer.

function normalizeArticleContent(raw: string): string {
  if (!raw) return ''
  let body = raw.trim()
  if (body.startsWith('<!-- SM_BLOCKS -->')) {
    body = body.replace('<!-- SM_BLOCKS -->', '').replace('<!-- /SM_BLOCKS -->', '').trim()
  }
  // Detect block JSON: starts with `{` and parses to an object with `blocks`
  if (body.startsWith('{')) {
    try {
      const doc = JSON.parse(body)
      if (Array.isArray(doc?.blocks)) {
        return blocksToHtml(doc.blocks)
      }
    } catch {
      // fall through — not JSON, treat as HTML
    }
  }
  return raw
}

function blocksToHtml(blocks: any[]): string {
  return blocks
    .map((block: any) => {
      const data = block?.data ?? {}
      switch (block?.type) {
        case 'paragraph':
          return data.html ? `<p>${data.html}</p>` : ''
        case 'heading': {
          const level = data.level || 2
          return data.text ? `<h${level}>${escapeHtml(data.text)}</h${level}>` : ''
        }
        case 'image': {
          if (!data.src) return ''
          const caption = data.caption ? `<figcaption>${escapeHtml(data.caption)}</figcaption>` : ''
          return `<figure><img src="${data.src}" alt="${escapeHtml(data.alt || '')}" loading="lazy" />${caption}</figure>`
        }
        case 'video':
          return data.url
            ? `<div class="video-embed"><iframe src="${data.url}" allowfullscreen loading="lazy"></iframe></div>`
            : ''
        case 'analysis':
          return data.html ? `<aside class="sm-analysis">${data.html}</aside>` : ''
        case 'scout-summary':
          return data.html
            ? `<aside class="scout-summary" style="border-left:4px solid #BC0000;background:rgba(0,0,0,0.04);border-radius:6px;padding:14px 16px;margin:16px 0;"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.1em;color:#6B7280;margin-bottom:6px;">Summary · AI-generated by Scout</div><div style="font-size:16px;line-height:1.6;">${data.html}</div></aside>`
            : ''
        case 'scout-recap':
          return data.html
            ? `<aside class="scout-recap" style="border:1px solid rgba(0,0,0,0.12);background:rgba(0,0,0,0.04);border-radius:6px;padding:14px 16px;margin:32px 0 16px;"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.1em;color:#6B7280;margin-bottom:6px;">Recap · AI-generated by Scout</div><div style="font-size:16px;line-height:1.6;">${data.html}</div></aside>`
            : ''
        case 'scout-insight':
          return data.insight
            ? `<div class="scout-insight" style="background:rgba(0,212,255,0.06);border:1px solid rgba(0,212,255,0.20);border-radius:12px;padding:16px 18px;margin:20px 0;"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.15em;color:#00D4FF;margin-bottom:8px;">⚡ Scout AI Insight</div><p style="font-size:15px;line-height:1.6;font-style:italic;margin:0;">&ldquo;${escapeHtml(data.insight)}&rdquo;</p></div>`
            : ''
        case 'hot-take':
          return data.text
            ? `<blockquote class="hot-take"><p>${escapeHtml(data.text)}</p></blockquote>`
            : ''
        case 'update':
          return data.text
            ? `<div class="update-block"><strong>UPDATE${data.timestamp ? ` ${escapeHtml(data.timestamp)}` : ''}:</strong> ${escapeHtml(data.text)}</div>`
            : ''
        case 'divider':
          return '<hr />'
        default:
          return ''
      }
    })
    .filter(Boolean)
    .join('\n')
}

function escapeHtml(s: string): string {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

// ─── Edge Insights inline splice ──────────────────────────────
// Insert EDGE INSIGHT cards after the paragraph indicated by
// each insight's `paragraph_index` (1-based). Insights with no
// position or out-of-bounds positions are skipped.

const EDGE_TYPE_CONFIG: Record<string, { label: string; icon: string }> = {
  stat: { label: 'STAT', icon: '📊' },
  trend: { label: 'TREND', icon: '📈' },
  prediction: { label: 'PREDICTION', icon: '🎯' },
  risk: { label: 'RISK', icon: '⚠️' },
  sentiment: { label: 'SENTIMENT', icon: '💭' },
}

function renderEdgeInsightHtml(insight: EdgeInsight): string {
  const cfg = EDGE_TYPE_CONFIG[insight.insight_type] || EDGE_TYPE_CONFIG.stat
  return `<div class="edge-insight" style="margin:28px 0;border-radius:12px;border:1px solid rgba(0,0,0,0.10);border-left:3px solid #00D4FF;padding:16px 20px;background:rgba(0,212,255,0.04);"><div style="display:flex;align-items:center;gap:8px;margin-bottom:8px;"><span style="font-size:10px;font-weight:700;letter-spacing:0.1em;color:#00D4FF;text-transform:uppercase;">⚡ EDGE INSIGHT</span><span style="font-size:10px;font-weight:600;letter-spacing:0.06em;color:#6B7280;padding:2px 6px;border-radius:4px;background:rgba(0,0,0,0.04);text-transform:uppercase;">${cfg.icon} ${cfg.label}</span></div><div style="font-size:15px;font-weight:600;line-height:1.4;margin-bottom:4px;">${escapeHtml(insight.title)}</div><div style="font-size:13px;line-height:1.5;opacity:0.85;">${escapeHtml(insight.summary)}</div></div>`
}

export function spliceEdgeInsights(html: string, insights: EdgeInsight[]): string {
  if (!html || !insights?.length) return html

  // Indexes immediately after each </p>
  const positions: number[] = []
  const re = /<\/p>/gi
  let m: RegExpExecArray | null
  while ((m = re.exec(html)) !== null) positions.push(m.index + m[0].length)
  if (positions.length === 0) return html

  // Sorted ascending; drop entries without a paragraph_index or out of bounds
  const sorted = insights
    .filter((i) => typeof i.paragraph_index === 'number' && (i.paragraph_index as number) >= 1)
    .sort((a, b) => (a.paragraph_index as number) - (b.paragraph_index as number))

  let result = html
  let offset = 0
  for (const insight of sorted) {
    const slot = (insight.paragraph_index as number) - 1
    if (slot < 0 || slot >= positions.length) continue
    const insertAt = positions[slot] + offset
    const insertHtml = renderEdgeInsightHtml(insight)
    result = result.slice(0, insertAt) + insertHtml + result.slice(insertAt)
    offset += insertHtml.length
  }
  return result
}

// Types matching the website's API responses
export interface Author {
  id: number
  display_name: string
  avatar_url?: string
}

export interface Category {
  slug: string
  name: string
}

export interface Post {
  id: number
  title: string
  slug: string
  excerpt: string | null
  featured_image: string | null
  published_at: string
  views: number
  importance_score: number
  author: Author
  category: Category
  final_score?: number
}

export interface LiveGame {
  game_id: string
  sport: string
  status: string
  game_start_time?: string | null
  game_time_display?: string | null
  home_team_name: string
  away_team_name: string
  home_team_abbr: string
  away_team_abbr: string
  home_logo_url?: string | null
  away_logo_url?: string | null
  home_score: number
  away_score: number
  period?: string | null
  period_label?: string | null
  clock?: string | null
  chicago_team: string
  is_chicago_home: boolean
}

export interface LiveGamesResponse {
  games: LiveGame[]
  count: number
  poll_interval_ms?: number
  timestamp?: string
}

export interface EdgeInsight {
  id: string
  article_id: string
  team: string
  insight_type: 'stat' | 'trend' | 'prediction' | 'risk' | 'sentiment'
  title: string
  summary: string
  confidence_score: number
  source: string
  metadata: Record<string, unknown>
  paragraph_index?: number | null
  created_at: string
}

export interface RiverItem {
  id: string
  type:
    | 'editorial'
    | 'poll'
    | 'chart'
    | 'hub_update'
    | 'box_score'
    | 'trade_proposal'
    | 'scout_summary'
    | 'trending_article'
    | 'debate'
    | 'video'
  team: string
  teamColor: string
  timestamp: string
  data: Record<string, unknown>
}

export interface FeedResponse {
  featured: Post | null
  topHeadlines: Post[]
  latestNews: Post[]
  teamSections: Record<string, Post[]>
  trending: Post[]
  riverItems?: RiverItem[]
  meta: {
    total: number
    viewedCount: number
    isAuthenticated: boolean
  }
}

export interface ArticleContent {
  id: number
  title: string
  slug: string
  content_html: string
  excerpt: string | null
  featured_image: string | null
  published_at: string
  views: number
  author: Author
  category: Category
  seo_title?: string
  seo_description?: string
  related_posts?: Post[]
}

export interface ChatMessage {
  id: string
  room_id: string
  user_id: string
  content: string
  content_type: 'text' | 'gif'
  gif_url?: string
  created_at: string
  user: {
    id: string
    username: string
    avatar_url?: string
    badge?: string
  }
}

export interface AskAIResponse {
  response: string
  source: string
  team?: string
  teamDisplayName?: string
  sport?: string
  suggestions?: string[]
  relatedArticles?: Post[]
}

export interface MobileConfig {
  ads: {
    enabled: boolean
    admob: {
      enabled: boolean
      ios_banner_id?: string
      ios_interstitial_id?: string
      android_banner_id?: string
      android_interstitial_id?: string
      interstitial_frequency: number // Show every N articles
    }
    custom: {
      enabled: boolean
      placements: {
        feed_top?: string    // Custom HTML/JS for feed top
        feed_inline?: string // Custom HTML/JS between articles
        article_top?: string
        article_bottom?: string
      }
    }
  }
  features: {
    fan_chat_enabled: boolean
    ask_ai_enabled: boolean
    push_notifications_enabled: boolean
    dark_mode_enabled: boolean
  }
  force_update?: {
    required: boolean
    min_version: string
    message: string
    store_url: string
  }
}

export interface Poll {
  id: string
  question: string
  options: { id: string; text: string; votes: number }[]
  total_votes: number
  user_voted?: string // Option ID user voted for
  expires_at?: string
}

class ApiClient {
  private baseUrl: string
  private authToken: string | null = null

  constructor(baseUrl: string) {
    this.baseUrl = baseUrl
  }

  setAuthToken(token: string | null) {
    this.authToken = token
  }

  getAuthToken(): string | null {
    return this.authToken
  }

  private async fetch<T>(
    endpoint: string,
    options: RequestInit = {}
  ): Promise<T> {
    const url = `${this.baseUrl}${endpoint}`

    const headers: Record<string, string> = {
      'Content-Type': 'application/json',
      'X-Client': 'sportsmockery-mobile',
      ...(options.headers as Record<string, string>),
    }

    if (this.authToken) {
      headers['Authorization'] = `Bearer ${this.authToken}`
    }

    const response = await fetch(url, {
      ...options,
      headers,
    })

    if (!response.ok) {
      const error = await response.json().catch(() => ({ error: 'Unknown error' }))
      throw new Error(error.error || `API error: ${response.status}`)
    }

    return response.json()
  }

  // ============================================
  // FEED & ARTICLES - Syncs with website content
  // ============================================

  /**
   * Get personalized feed
   * Returns fresh content from the website
   */
  async getFeed(options?: {
    viewedIds?: number[]
    teamPreferences?: string[]
    onlySelectedTeams?: boolean
  }): Promise<FeedResponse> {
    if (options?.viewedIds || options?.teamPreferences) {
      return this.fetch<FeedResponse>('/api/feed', {
        method: 'POST',
        body: JSON.stringify({
          viewed_ids: options.viewedIds || [],
          team_preferences: options.teamPreferences || [],
          only_selected_teams: options.onlySelectedTeams || false,
        }),
      })
    }
    return this.fetch<FeedResponse>('/api/feed')
  }

  /**
   * Get full article content by ID
   * Always fetches fresh from website
   */
  async getArticle(articleId: number): Promise<ArticleContent> {
    const response = await this.fetch<{ post: any }>(`/api/posts/${articleId}`)
    const post = response.post

    // Supabase joins can return either an object or a single-element array
    // depending on relationship config — normalize both.
    const rawAuthor = Array.isArray(post.author) ? post.author[0] : post.author
    const rawCategory = Array.isArray(post.category) ? post.category[0] : post.category

    return {
      id: post.id,
      title: post.title,
      slug: post.slug,
      content_html: normalizeArticleContent(post.content || ''),
      excerpt: post.excerpt,
      featured_image: post.featured_image,
      published_at: post.published_at,
      views: post.views || 0,
      author: rawAuthor
        ? {
            id: rawAuthor.id ?? 0,
            display_name: rawAuthor.display_name || 'Staff',
            avatar_url: rawAuthor.avatar_url,
          }
        : { id: 0, display_name: 'Staff' },
      category: rawCategory
        ? { slug: rawCategory.slug || 'news', name: rawCategory.name || 'News' }
        : { slug: 'news', name: 'News' },
      seo_title: post.seo_title,
      seo_description: post.seo_description,
      related_posts: [],
    }
  }

  /**
   * Fetch the current set of Chicago live/upcoming games.
   * Used by the home-feed live pill.
   */
  async getLiveGames(): Promise<LiveGamesResponse> {
    try {
      return await this.fetch<LiveGamesResponse>('/api/live-games')
    } catch {
      return { games: [], count: 0 }
    }
  }

  /**
   * Fetch EDGE Insights for an article. Insights carry a paragraph_index
   * indicating where they should be spliced inline.
   */
  async getEdgeInsights(articleId: number | string): Promise<EdgeInsight[]> {
    try {
      const res = await this.fetch<{ insights?: EdgeInsight[] }>(
        `/api/edge-insights?article_id=${articleId}`
      )
      return res.insights ?? []
    } catch {
      return []
    }
  }

  /**
   * Get articles by category/team
   */
  async getTeamArticles(
    teamSlug: string,
    options?: { page?: number; limit?: number }
  ): Promise<{ posts: Post[]; hasMore: boolean }> {
    const params = new URLSearchParams()
    if (options?.page) params.set('page', options.page.toString())
    if (options?.limit) params.set('limit', options.limit.toString())

    return this.fetch(`/api/team/${teamSlug}?${params}`)
  }

  /**
   * Record article view (for analytics and personalization)
   */
  async recordView(postId: number): Promise<void> {
    await this.fetch(`/api/views/${postId}`, { method: 'POST' })
  }

  // ============================================
  // FAN CHAT - Real-time via Supabase
  // ============================================

  /**
   * Get chat messages for a room
   */
  async getChatMessages(
    roomId: string,
    options?: { before?: string; limit?: number }
  ): Promise<{ messages: ChatMessage[]; hasMore: boolean }> {
    const params = new URLSearchParams({ roomId })
    if (options?.before) params.set('before', options.before)
    if (options?.limit) params.set('limit', options.limit.toString())

    return this.fetch(`/api/chat/messages?${params}`)
  }

  /**
   * Send a chat message
   */
  async sendChatMessage(
    roomId: string,
    content: string,
    options?: { contentType?: 'text' | 'gif'; gifUrl?: string; replyToId?: string }
  ): Promise<{ success: boolean; message: ChatMessage }> {
    return this.fetch('/api/chat/messages', {
      method: 'POST',
      body: JSON.stringify({
        roomId,
        content,
        contentType: options?.contentType || 'text',
        gifUrl: options?.gifUrl,
        replyToId: options?.replyToId,
      }),
    })
  }

  // ============================================
  // ASK AI - Proxied through website
  // ============================================

  /**
   * Ask the Mockery AI a question
   */
  async askAI(query: string): Promise<AskAIResponse> {
    return this.fetch('/api/ask-ai', {
      method: 'POST',
      body: JSON.stringify({ query }),
    })
  }

  // ============================================
  // POLLS
  // ============================================

  /**
   * Get a poll by ID
   */
  async getPoll(pollId: string): Promise<Poll> {
    return this.fetch(`/api/polls/${pollId}`)
  }

  /**
   * Vote on a poll
   */
  async votePoll(pollId: string, optionId: string): Promise<Poll> {
    return this.fetch(`/api/polls/${pollId}/vote`, {
      method: 'POST',
      body: JSON.stringify({ optionId }),
    })
  }

  // ============================================
  // MOBILE CONFIG - Ad settings, feature flags
  // ============================================

  /**
   * Get mobile app configuration
   * Includes ad settings controlled from admin panel
   */
  async getMobileConfig(): Promise<MobileConfig> {
    return this.fetch('/api/mobile/config')
  }

  // ============================================
  // TEAM DATA - Rosters, schedules, stats
  // ============================================

  /**
   * Get Bears roster
   */
  async getBearsRoster(): Promise<any> {
    return this.fetch('/api/bears/roster')
  }

  /**
   * Get Bears schedule
   */
  async getBearsSchedule(): Promise<any> {
    return this.fetch('/api/bears/schedule')
  }

  /**
   * Get Bears stats
   */
  async getBearsStats(): Promise<any> {
    return this.fetch('/api/bears/stats')
  }

  // ============================================
  // SEARCH
  // ============================================

  /**
   * Search articles
   */
  async search(query: string, options?: { team?: string; limit?: number }): Promise<Post[]> {
    const params = new URLSearchParams({ q: query })
    if (options?.team) params.set('team', options.team)
    if (options?.limit) params.set('limit', options.limit.toString())

    const response = await this.fetch<{ results: Post[] }>(`/api/search?${params}`)
    return response.results
  }

  // ============================================
  // AUDIO
  // ============================================

  /**
   * Get audio URL for an article
   */
  getAudioUrl(slug: string, voice: string = 'will'): string {
    return `${this.baseUrl}/api/audio/${slug}?voice=${voice}`
  }

  /**
   * Get next article for audio playlist
   */
  async getNextAudioArticle(
    currentArticleId: number,
    mode: 'team' | 'recent',
    team?: string
  ): Promise<{ id: number; title: string; slug: string; team?: string } | null> {
    const params = new URLSearchParams({
      articleId: currentArticleId.toString(),
      mode,
    })
    if (team) params.set('team', team)

    try {
      const response = await this.fetch<{
        article: { id: number; title: string; slug: string; team?: string } | null
      }>(`/api/audio/next?${params}`)
      return response.article
    } catch (err) {
      console.error('Failed to get next audio article:', err)
      return null
    }
  }

  /**
   * Get first article for audio playlist
   */
  async getFirstAudioArticle(
    mode: 'team' | 'recent',
    team?: string
  ): Promise<{ id: number; title: string; slug: string; team?: string } | null> {
    try {
      if (mode === 'team' && team) {
        // Support comma-separated teams — fetch from all and pick most recent by publish date
        const teams = team.split(',').filter(Boolean)
        const results = await Promise.all(
          teams.map(async (t) => {
            const response = await this.getTeamArticles(t.trim(), { limit: 3 })
            return (response.posts || []).map((post: Post) => ({
              id: post.id,
              title: post.title,
              slug: post.slug,
              team: t.trim(),
              published_at: post.published_at,
            }))
          })
        )
        const allPosts = results.flat().sort(
          (a, b) => new Date(b.published_at).getTime() - new Date(a.published_at).getTime()
        )
        if (allPosts.length > 0) {
          const { id, title, slug, team: postTeam } = allPosts[0]
          return { id, title, slug, team: postTeam }
        }
      } else {
        // Get first recent article
        const response = await this.getFeed()
        if (response.latestNews && response.latestNews.length > 0) {
          const post = response.latestNews[0]
          return { id: post.id, title: post.title, slug: post.slug }
        }
      }
      return null
    } catch (err) {
      console.error('Failed to get first audio article:', err)
      return null
    }
  }
}

// Export singleton instance
export const api = new ApiClient(API_BASE_URL)

// Export class for testing
export { ApiClient }
